languageCode = 'en-us'
baseurl = "https://www.cinderblook.com/"
metaDataFormat = "yaml"
title = "Austin Barnes"
theme = "blist"

DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = true

[params]
  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = true

  # Custom copyright - optional
  copyright = "Copyright © 2021 - Austin Barnes · All rights reserved"
  favicon = "/favicon.svg"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-100"

  # The page bundle that is shown on the front page
  frontBundle = "blog"
  # Front Page
  introTitle = "Hey! I'm Austin"
  introSubtitle = "21 y/o Network Technician who enjoys the outdoors, flying drones, homelabbing, and of course, all things tech."
  introPhoto = "/Portrait_Austin.jpg"
  #logo = "/portrait_Austin.jpg"

[params.homepage.social]
  # Global params 
  title = "Follow me"
  description = "I put a little bit of everything on here, so follow along in my journey if you wish"
  linkedin = "https://www.linkedin.com/in/austin-barnes-03869218a/"
  instagram = "https://www.instagram.com/austin_barnesz/"
  github = "https://github.com/Cinderblook"
  coffeescript = "https://www.buymeacoffee.com/cinderblook"
  
 [[menu.main]]
     name = "Blog"
     url = "blog"
     weight = 1
 [[menu.main]]
     name = "About"
     url = "page/about/"
     weight = 2
 [[menu.main]]
     name = "Tags"
     url = "tags"
     weight = 3
 [[menu.main]]
     name = "Sites"
     url = "page/sites/"
     weight = 4

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
